export const REACTION_EMOJIS = ['😀', '😂', '😮', '😢', '😡', '👏', '🔥', '🎉'] as const

export type ReactionEmoji = (typeof REACTION_EMOJIS)[number]

export const REACTION_PHRASE_GROUPS = [
  {
    id: 'waiting',
    label: 'Waiting...',
    phrases: [
      'We’re waitiiinnggg…',
      'Clock’s ticking!',
      'Any day now…',
      'Just pick one 😄',
      'Don’t overthink it!',
      'Make it count!',
      'Take your time… we’ve got all night 😄',
      'Should we send help?',
      'The suspense is killing me.',
      'We aging over here.',
      'You writing a thesis or playing a card?',
      'Alright, dramatic pause noted.',
      'You good over there?',
      'Need a hint?',
      'Decisions, decisions…',
      'Consulting the oracle?',
      'That hand that tough?',
      'Pressure’s on!',
      'We believe in you… kinda.',
      'This better be good.',
    ],
  },
  {
    id: 'praise',
    label: 'Praise',
    phrases: [
      'Well played.',
      'Respect.',
      'You earned that one.',
      'Good play, not gonna lie.',
      'Not bad, not bad.',
      'Alright, I see you.',
      'Lucky… but I’ll allow it.',
      'You got away with one there.',
      'Okay, now I’m annoyed 😄',
      'That woke me up.',
      'Enjoy it while it lasts.',
    ],
  },
  {
    id: 'fight',
    label: 'Fight',
    phrases: [
      'Don’t get used to it.',
      'This means war.',
      'You just made it personal.',
      'Alright, now I’m locked in.',
      'I’ll remember that.',
      'You’re on borrowed time.',
      'Next one\'s mine.',
      'Game on.',
      'You’re gonna regret that.',
    ],
  },
  {
    id: 'confident',
    label: 'Confident',
    phrases: [
      'I like my chances here.',
      'Hope you came prepared.',
      'This might get ugly.',
      'I’ve been waiting for this.',
      'Big battle coming up.',
      'Let’s see who’s brave.',
      'I wouldn’t bid against me.',
      'You sure you wanna do that?',
      'That’s how it’s done.',
      'Skill. Pure skill.',
      'I had a plan the whole time.',
      'Just warming up.',
      'Oh, this is gonna be fun.',
      'Y’all are in danger.',
    ],
  },
  {
    id: 'brag',
    label: 'Brag',
    phrases: [
      'That’s how it’s done.',
      'Skill. Pure skill.',
      'I had a plan the whole time.',
      'Just warming up.',
      'Let’s gooo!',
      'Momentum shift, baby.',
      'Right where I want to be.',
      'That one was mine.',
      'I’ll take that, thank you very much.',
      'Never in doubt… mostly.',
      'I was sandbagging a little 😉',
      'Had to keep it interesting.',
      'All part of the strategy.',
      'Calculated. Completely calculated.',
      'Interesting… very interesting.',
      'I’ve got options.',
      'That might work… for me.',
      'I’m okay with this.',
    ],
  },
  {
    id: 'nervous',
    label: 'Nervous',
    phrases: [
      'This hand is tragic.',
      'I got nothing, honestly.',
      'I’m just here for moral support.',
      'Don’t worry about me.',
      'I’m folding in spirit.',
      'This is gonna hurt.',
      'I should’ve stayed home.',
      'I’ve seen better hands in Uno.',
      'Yeah… I’m in trouble.',
      'Not gonna lie, I was sweatin\'.',
      'Whew… survived that one.',
      'You almost had me there.',
      'Y’all are safe this time.',
    ],
  },
  {
    id: 'relief',
    label: 'Relief',
    phrases: [
      'Not gonna lie, I was sweatin\'.',
      'Whew… survived that one.',
      'You almost had me there.',
      'Okay yeah, that felt good.',
      'I needed that.',
      'Clutched it.',
    ],
  },
  {
    id: 'frustrated',
    label: 'Frustrated',
    phrases: [
      'Bold move.',
      'Are you serious!?',
      'You gotta be kidding me!',
      'Oh, come on.',
      'That is ridiculous.',
      'No way that just happened.',
      'You cannot be for real right now.',
      'That is so annoying.',
      'Unbelievable.',
      'I did not need that.',
      'Really? Really?',
      'That changes things.',
      'I didn’t expect that.',
      'We’ll see how this plays out.',
      'Keep going…',
    ],
  },
  {
    id: 'bidding',
    label: 'Bidding',
    phrases: [
      'Let’s keep this reasonable…',
      'I’m thinking conservative… maybe.',
      'I’ve seen worse bets.',
      'That’s either genius or a disaster.',
      'Who’s feeling bold?',
      'That’s a spicy bid.',
      'Push it higher, I dare you.',
      'Alright, gloves off.',
      'Go big or go home.',
      'Someone’s overconfident.',
      'You sure about that number?',
      'I’m not scared of that.',
      'Sandbagging already?',
      'This is where it gets real.',
      'I’m calling your bluff already.',
    ],
  },
] as const

export type ReactionPhraseGroup = (typeof REACTION_PHRASE_GROUPS)[number]
export type ReactionPhraseGroupId = ReactionPhraseGroup['id']
export type ReactionPhrase = ReactionPhraseGroup['phrases'][number]

export const REACTION_PHRASES = REACTION_PHRASE_GROUPS.flatMap((group) => group.phrases)
