export function buildHomeProps({
  buildTimestampLabel,
  canInstallApp,
  isStagingBuild,
  promptToInstall,
  requestError,
  sessionInfo,
}) {
  return {
    buildTimestampLabel,
    canInstallApp,
    isStagingBuild,
    promptToInstall,
    requestError,
    sessionInfo,
  }
}

export function buildLobbyProps({
  gameError,
  handleCopyShareLink,
  handleRenamePlayer,
  isRenamingPlayer,
  isShareLinkCopied,
  isStartingGame,
  lobby,
  lobbyInfo,
  openLobbyRemovePlayerConfirm,
  openLobbyRemoveSeatConfirm,
  openLobbyRenamePlayerModal,
  ownerSession,
  pendingPlayerActionId,
  resetActiveSessionState,
  selectedAiDifficulty,
  selectedMaxCards,
  setSelectedAiDifficulty,
  setSelectedMaxCards,
  shareQrCodeDataUrl,
}) {
  return {
    activeLobbyPlayerId: lobby.activeLobbyPlayerId,
    activeLobbySession: lobby.activeLobbySession,
    aiDifficultyOptions: lobby.aiDifficultyOptions,
    currentDealerPlayerId: lobby.currentDealerPlayerId,
    gameError,
    handleAddSeat: lobby.handleAddSeat,
    handleCopyShareLink,
    handleMovePlayer: lobby.handleMovePlayer,
    handleRemovePlayer: lobby.handleRemovePlayer,
    handleRemoveSeat: lobby.handleRemoveSeat,
    handleRenamePlayer,
    handleStartGame: lobby.handleStartGame,
    isLocalPlayerMarkedAway: lobby.isLocalPlayerMarkedAway,
    isOwnerLobby: lobby.isOwnerLobby,
    isRenamingPlayer,
    isShareLinkCopied,
    isStartingGame,
    lobbyInfo,
    maxCardsForLobbySeatCount: lobby.maxCardsForLobbySeatCount,
    maxSeats: lobby.maxSeats,
    openLobbyRemovePlayerConfirm,
    openLobbyRemoveSeatConfirm,
    openLobbyRenamePlayerModal,
    orderedPlayers: lobby.orderedPlayers,
    ownerSession,
    pendingPlayerActionId,
    resetActiveSessionState,
    selectedAiDifficulty,
    selectedMaxCards,
    setSelectedAiDifficulty,
    setSelectedMaxCards,
    shareLink: lobby.shareLink,
    shareQrCodeDataUrl,
  }
}

export function buildActiveGameProps({
  gameError,
  handleCopyShareLink,
  handleCoverAwayPlayerTurn,
  handleDealCards,
  handleLeaveGame,
  handleOpenJoinGame,
  handleOpenNewGame,
  handlePlayCard,
  handleRenamePlayer,
  handleSendReaction,
  handleStartOver,
  isDealingCards,
  isLeavingGame,
  isPlayingCard,
  isReactionOnCooldown,
  isSendingReaction,
  isShareLinkCopied,
  isSortingCards,
  isStartingOver,
  lobby,
  openHelpModal,
  openSubmitBidModal,
  ownerSession,
  pendingPlayerActionId,
  promptToInstall,
  resetActiveSessionState,
  setGameError,
  sortMode,
  toggleSortCards,
}) {
  return {
    errorMessage: gameError,
    game: lobby.activeGame,
    isDealingCards,
    isLeavingGame,
    isLocalPlayerMarkedAway: lobby.isLocalPlayerMarkedAway,
    isOwner: Boolean(ownerSession),
    isPlayingCard,
    isReactionOnCooldown,
    isSendingReaction,
    isShareLinkCopied,
    isSortingCards,
    isStartingOver,
    onCopyShareLink: handleCopyShareLink,
    onCoverAwayPlayerTurn: handleCoverAwayPlayerTurn,
    onDealCards: handleDealCards,
    onGoHome: resetActiveSessionState,
    onInstallApp: promptToInstall,
    onLeaveGame: handleLeaveGame,
    onOpenHelp: openHelpModal,
    onOpenJoinGame: handleOpenJoinGame,
    onOpenNewGame: handleOpenNewGame,
    onPlayCard: handlePlayCard,
    onRemovePlayer: lobby.handleRemovePlayer,
    onRenamePlayer: handleRenamePlayer,
    onSendReaction: handleSendReaction,
    onSetGameError: setGameError,
    onSortCards: toggleSortCards,
    onStartOver: handleStartOver,
    onSubmitBid: openSubmitBidModal,
    ownerPlayerId: ownerSession?.ownerPlayerId ?? '',
    pendingPlayerActionId,
    shareLink: lobby.shareLink,
    sortMode,
  }
}

export function buildModalProps({
  closeHelpModal,
  closeLobbyRemovePlayerConfirm,
  closeLobbyRemoveSeatConfirm,
  closeLobbyRenamePlayerModal,
  closeLobbyShareModal,
  closeSubmitBidModal,
  createErrors,
  handleCloseCreateModal,
  handleCloseJoinModal,
  handleContinueGame,
  handleCreateGame,
  handleCreatePlayerNameInputChange,
  handleJoinGame,
  handleJoinGameIdInputChange,
  handleJoinPlayerNameInputChange,
  handleRejoinSelectionChange,
  handleSubmitBid,
  helpSection,
  isBidModalOpen,
  isContinuingGame,
  isCreateModalOpen,
  isCreatingGame,
  isEndOfRoundModalDismissed,
  isHelpModalOpen,
  isJoinModalOpen,
  isJoiningGame,
  isLoadingRejoinGames,
  isLobbyShareModalOpen,
  isRejoiningGame,
  isSubmittingBid,
  joinErrors,
  joinGameId,
  joinMenuCloseRequestKey,
  joinPlayerName,
  lobby,
  lobbyRenameDraft,
  openCreateModal,
  openHelpModal,
  openJoinModal,
  openLobbyShareModal,
  pendingLobbyRemovePlayer,
  pendingLobbyRemoveSeat,
  pendingLobbyRenamePlayer,
  persistedEndOfRoundSummary,
  playerName,
  rejoinableGames,
  resetCreateDraft,
  resetJoinDraft,
  selectedBid,
  selectedRejoinGameId,
  setHelpSection,
  setIsEndOfRoundModalDismissed,
  setLobbyRenameDraft,
  setSelectedBid,
  showAwayContinueModal,
}) {
  return {
    awayContinue: {
      isContinuingGame,
      isOpen: showAwayContinueModal,
      onContinue: handleContinueGame,
    },
    bid: {
      currentRoundCardCount: lobby.currentRoundCardCount,
      isOpen: isBidModalOpen,
      isSubmittingBid,
      isTripRound: lobby.isTripRound,
      onClose: closeSubmitBidModal,
      onSubmit: handleSubmitBid,
      selectedBid,
      setSelectedBid,
    },
    createGame: {
      form: {
        isCreatingGame,
        onPlayerNameChange: handleCreatePlayerNameInputChange,
        playerName,
        playerNameError: createErrors.playerName,
      },
      isOpen: isCreateModalOpen,
      onClose: handleCloseCreateModal,
      onOpen: () => {
        resetCreateDraft()
        openCreateModal()
      },
      onSubmit: handleCreateGame,
    },
    endOfRound: {
      isDismissed: isEndOfRoundModalDismissed,
      onClose: () => setIsEndOfRoundModalDismissed(true),
      summary: persistedEndOfRoundSummary,
    },
    help: {
      helpSection,
      isOpen: isHelpModalOpen,
      onClose: closeHelpModal,
      onOpen: openHelpModal,
      setHelpSection,
    },
    joinGame: {
      form: {
        isJoiningGame,
        isLoadingRejoinGames,
        isRejoiningGame,
        joinErrors,
        joinGameId,
        joinPlayerName,
        onJoinGameIdChange: handleJoinGameIdInputChange,
        onJoinPlayerNameChange: handleJoinPlayerNameInputChange,
        onSelectedRejoinGameIdChange: handleRejoinSelectionChange,
        rejoinableGames,
        selectedRejoinGameId,
      },
      isOpen: isJoinModalOpen,
      menuCloseRequestKey: joinMenuCloseRequestKey,
      onClose: handleCloseJoinModal,
      onOpen: () => {
        resetJoinDraft()
        openJoinModal()
      },
      onSubmit: handleJoinGame,
    },
    lobbyRemovePlayer: {
      onClose: closeLobbyRemovePlayerConfirm,
      pendingPlayer: pendingLobbyRemovePlayer,
    },
    lobbyRemoveSeat: {
      onClose: closeLobbyRemoveSeatConfirm,
      pendingPlayer: pendingLobbyRemoveSeat,
    },
    lobbyRenamePlayer: {
      draftValue: lobbyRenameDraft,
      onClose: closeLobbyRenamePlayerModal,
      pendingPlayer: pendingLobbyRenamePlayer,
      setDraftValue: setLobbyRenameDraft,
    },
    lobbyShare: {
      isOpen: isLobbyShareModalOpen,
      onClose: closeLobbyShareModal,
      onOpen: openLobbyShareModal,
    },
  }
}
