export const BOT_NAMES: readonly string[] = [
  "Quick Draw",
  "Sharp Shuffle",
  "Deadly Weapon",
  "Ace Machine",
  "Trick Snatcher",
  "Silent Killer",
  "Cold Dealer",
  "Perfect Timing",
  "Steel Nerves",
  "Final Word",
  "Poker Face",
  "Honest Liar",
  "Bluff Master",
  "Stone Cold",
  "Double Cross",
  "Quiet Threat",
  "Smiling Assassin",
  "Friendly Enemy",
  "Sweet Deceiver",
  "Calm Chaos",
  "Freaky Fingers",
  "Lightning Hands",
  "Rapid Fire",
  "Turbo Mind",
  "Flashpoint",
  "Snap Decision",
  "Wild Card",
  "Hot Streak",
  "Zero Chill",
  "Full Tilt",
  "Card Reaper",
  "The Punisher",
  "Risk Taker",
  "Chaos Dealer",
  "Fate Breaker",
  "Rule Bender",
  "Heartbreaker",
  "The Unlucky Charm",
  "Bad Omen",
  "Trouble Maker",
  "Brain Burner",
  "The Analyst",
  "Quiet Genius",
  "Pattern Breaker",
  "Mind Maze",
  "Logic Trap",
  "The Accountant",
  "Probability Pirate",
  "The Schemer",
  "Tiebreak Tyrant",
  "Wiggly Winner",
  "Floppy Fingers",
  "Captain Cardboard",
  "Mister Misdeal",
  "Queen of Chaos",
  "The Shufflin\u2019 Muffin",
  "Lucky Duckling",
  "The Mild Threat",
  "Sir Trips-A-Lot",
  "The Almost Champion",
  "Bluffalo Bill",
  "The Card Cactus",
  "The Foldinator",
  "Sneaky Beaky",
  "Big Deal Banana",
  "The Fumble Wizard",
  "Count Clueless",
  "The Panic Button",
  "Mister Maybe",
  "Jokester Supreme",
  "The Wiggly Wizard",
  "Sneak-Attack Snack",
  "The Goof Gambler",
  "Pocket-Sized Menace",
  "The Tiny Titan",
  "The Card Bard",
  "The Mild Menace",
  "The Sassy Shuffler",
  "The Chaotic Neutral",
  "Marshmallow Fury",
  "Bubblegum Bandit",
  "Cinnamon Spin",
  "The Cozy Crusher",
  "Peanut Butter Panic",
  "The Gentle Jerk",
  "Cupcake Carnage",
  "The Snuggle Striker",
  "Fluffy Havoc",
  "The Velvet Villain",
  "The Unstable Genius",
  "Chaos Cupholder",
  "The Accidental Winner",
  "The Cardboard Overlord",
  "The Friendly Disaster",
  "The Wobble King",
  "The Slightly Dangerous",
  "The Mostly Harmless",
  "The Wild Guess",
  "The Sandbagger",
] ;

export const getBotName = (
  existingNames: string[],
  preferredIndex = 0,
): string => {
  const usedNames = new Set(existingNames);
  const startIndex = ((preferredIndex % BOT_NAMES.length) + BOT_NAMES.length) % BOT_NAMES.length;

  for (let offset = 0; offset < BOT_NAMES.length; offset += 1) {
    const candidateName = BOT_NAMES[(startIndex + offset) % BOT_NAMES.length];
    if (!usedNames.has(candidateName)) {
      return candidateName;
    }
  }

  return BOT_NAMES[startIndex];
};
