export const BOT_NAMES: readonly string[] = [
  "Quick Draw",
  "Sharp Shuffle",
  "Deadly Weapon",
  "Ace Machine",
  "Trick Snatcher",
  "Silent Killer",
  "Cold Dealer",
  "Perfect Timing",
  "Steel Nerves",
  "Final Word",
  "Poker Face",
  "Honest Liar",
  "Bluff Master",
  "Stone Cold",
  "Double Cross",
  "Quiet Threat",
  "Smiling Assassin",
  "Friendly Enemy",
  "Sweet Deceiver",
  "Calm Chaos",
  "Freaky Fingers",
  "Lightning Hands",
  "Rapid Fire",
  "Turbo Mind",
  "Flashpoint",
  "Snap Decision",
  "Wild Card",
  "Hot Streak",
  "Zero Chill",
  "Full Tilt",
  "Card Reaper",
  "The Punisher",
  "Risk Taker",
  "Chaos Dealer",
  "Fate Breaker",
  "Rule Bender",
  "Heartbreaker",
  "Unlucky Charm",
  "Bad Omen",
  "Trouble Maker",
  "Brain Burner",
  "The Analyst",
  "Quiet Genius",
  "Pattern Breaker",
  "Mind Maze",
  "Logic Trap",
  "The Accountant",
  "Probability Pirate",
  "The Schemer",
  "Tiebreak Tyrant",
  "Wiggly Winner",
  "Floppy Fingers",
  "Captain Cardboard",
  "Mister Misdeal",
  "Queen of Chaos",
  "Shufflin\u2019 Muffin",
  "Lucky Duckling",
  "Mild Threat",
  "Sir Trips-A-Lot",
  "Almost Champion",
  "Bluffalo Bill",
  "Card Cactus",
  "The Foldinator",
  "Sneaky Beaky",
  "Big Deal Banana",
  "Fumble Wizard",
  "Count Clueless",
  "Panic Button",
  "Mister Maybe",
  "Jokester Supreme",
  "Wiggly Wizard",
  "Sneak-Attack Snack",
  "Goof Gambler",
  "Pocket-Sized Menace",
  "Tiny Titan",
  "Card Bard",
  "Mild Menace",
  "Sassy Shuffler",
  "Chaotic Neutral",
  "Marshmallow Fury",
  "Bubblegum Bandit",
  "Cinnamon Spin",
  "Cozy Crusher",
  "Peanut Butter Panic",
  "Humble Jerk",
  "Cupcake Carnage",
  "Snuggle Striker",
  "Fluffy Havoc",
  "Velvet Villain",
  "Unstable Genius",
  "Chaos Cupholder",
  "Accidental Winner",
  "Cardboard Overlord",
  "Friendly Disaster",
  "Wobble King",
  "Slightly Dangerous",
  "Mostly Harmless",
  "Wild Guess",
  "The Sandbagger",
] ;

export const getBotName = (existingNames: string[]): string => {
  const usedNames = new Set(existingNames);
  const availableNames = BOT_NAMES.filter((name) => !usedNames.has(name));
  const candidatePool = availableNames.length > 0 ? availableNames : BOT_NAMES;
  const randomIndex = Math.floor(Math.random() * candidatePool.length);

  return candidatePool[randomIndex];
};
